// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:wild_dare_randomizer/features/rules/domain/entities/rule_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(RandomValueAdapter());
    registerAdapter(RuleEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(RandomValueAdapter());
    registerAdapter(RuleEntityAdapter());
  }
}
